# Generated by Django 4.2.3 on 2024-05-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rssentry_matched_words_rssentry_passed_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrytags',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entrytags',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='rssentry',
            name='tags',
        ),
        migrations.DeleteModel(
            name='EntryTag',
        ),
        migrations.DeleteModel(
            name='EntryTags',
        ),
    ]
