# Generated by Django 4.2.3 on 2023-07-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='last_parse_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего парсинга'),
        ),
    ]
