# Generated by Django 4.2.3 on 2024-05-05 18:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content_filter', '0002_alter_keyword_text'),
        ('telegram', '0002_telegramchannel_last_parse_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='use_global_keywords',
            field=models.BooleanField(default=True, help_text='Отметьте если хотите, чтобы глобальные ключевые словаиспользовались при фильтрации контента', verbose_name='Использовать глобальные ключевые слова?'),
        ),
        migrations.CreateModel(
            name='CustomChannelKeywords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channels_data', to='content_filter.keyword', verbose_name='Ключевое слово')),
                ('telegram_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_keywords_data', to='telegram.telegramchannel', verbose_name='Telegram канал')),
            ],
            options={
                'verbose_name': 'Отдельное ключевое слово',
                'verbose_name_plural': 'Отдельные ключевые слова',
                'ordering': ('telegram_channel', 'keyword'),
            },
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='custom_keywords',
            field=models.ManyToManyField(related_name='telegram_channels', through='telegram.CustomChannelKeywords', to='content_filter.keyword', verbose_name='Ключевые слова'),
        ),
    ]
